# .github/workflows/example.yml
name: Example
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Mask fruit
      uses: pitoniak32/rust-action@main
      with:
        fruit: banana

    - name: Echo fruit
      run: echo "apple, banana, and orange"
